### ISSUE TITLE
Make whole row clickable

### ISSUE THREAD

**Issue by blinry** [jeffro94/best-books#5]
I know this is kind of a pain to restructure things like that, but I really like it when you can click anywhere in the row of a table to go to the linked item! :)

**Comment by jeffro94** [comment]
I actually started with this approach! I switched to the current config for a few reasons:
- enabling click via the whole row necessitated implementing the redirect via javascript. users didn't have the option of clicking through directly vs opening the book detail page in a new tab or window
- switching the link to only be the title wrapped in <a> is more semantically correct html and works more smoothly with React router
- leaving the author unlinked leaves room for linking to a separate "author" detail page in the future

closing this for now but I had similar thoughts and thanks for the feedback!

**Comment by blinry** [comment]
Especially the last reason is actually very convincing! :)
